#file: noinspection SpellCheckingInspection
spring:
  application:
    name: banksecurity
  datasource:
    url: jdbc:mysql://springsecurity.cxomioiaadxx.ap-south-1.rds.amazonaws.com/eazybank
    username: admin
    password: JavaDevlop3r2024!
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: DEBUG